module ElasticGraph
  module SchemaDefinition
    module Indexing
      # Note: this is a partial signature definition (`index.rb` is ignored in `Steepfile`)
      class Index
        attr_reader name: ::String
        attr_reader routing_field_path: SchemaElements::FieldPath?
        attr_reader rollover_config: RolloverConfig?
        attr_reader has_had_multiple_sources_flag: bool
        attr_reader indexed_type: indexableType
        attr_reader nested_sourced_paths: ::Hash[::String, ::Array[SchemaArtifacts::RuntimeMetadata::nestedSourcedPathSegment]]

        def uses_custom_routing?: () -> bool
        def register_nested_sourced_paths: (::String, ::Array[SchemaArtifacts::RuntimeMetadata::nestedSourcedPathSegment]) -> void
        def to_index_config: () -> ::Hash[::String, untyped]
        def to_index_template_config: () -> ::Hash[::String, untyped]
        def runtime_metadata: () -> SchemaArtifacts::RuntimeMetadata::IndexDefinition

        private

        def date_and_datetime_types: () -> ::Array[::String]
      end
    end
  end
end
