module ElasticGraph
  module SchemaDefinition
    module Indexing
      class ResolvedRelationshipChainSuperType
        attr_reader relationships: ::Array[SchemaElements::Relationship]
        attr_reader path_segments: ::Array[PathSegment]

        def initialize: (
          relationships: ::Array[SchemaElements::Relationship],
          path_segments: ::Array[PathSegment]
        ) -> void
      end

      class ResolvedRelationshipChain < ResolvedRelationshipChainSuperType
        def root_relationship: () -> SchemaElements::Relationship
        def leaf_relationship: () -> SchemaElements::Relationship
        def root_index: () -> Index
        def register_on_root_index: () -> void
        @qualified_relationship: ::String
        def qualified_relationship: () -> ::String
        @sourced_from_nested_paths: ::Array[SchemaArtifacts::RuntimeMetadata::sourcedFromNestedPathSegment]
        def sourced_from_nested_paths: () -> ::Array[SchemaArtifacts::RuntimeMetadata::sourcedFromNestedPathSegment]
        @path_identifier_params: ::Hash[::String, SchemaArtifacts::RuntimeMetadata::DynamicParam]
        def path_identifier_params: () -> ::Hash[::String, SchemaArtifacts::RuntimeMetadata::DynamicParam]
      end

      class PathSegment
        attr_reader field: SchemaElements::Field
        attr_reader source_field_name: ::String?

        def initialize: (
          field: SchemaElements::Field,
          source_field_name: ::String?
        ) -> void
      end

      class RelationshipChainResolver
        @schema_def_state: State
        @indexing_fields_by_field_type_name_by_parent_type: ::Hash[indexableType, ::Hash[::String, ::Array[SchemaElements::Field]]]

        def initialize: (schema_def_state: State) -> void
        def resolve: (SchemaElements::Relationship) -> [ResolvedRelationshipChain?, ::Array[::String]]

        private

        def resolve_chain: (
          SchemaElements::Relationship,
          ::Array[PathSegment],
          ::Array[SchemaElements::Relationship],
          ::Array[::String]
        ) -> SchemaElements::Relationship?

        def resolve_parent_ref: (
          SchemaElements::Relationship,
          SchemaElements::Relationship::ParentRef,
          ::Array[SchemaElements::Relationship],
          ::Array[::String]
        ) -> SchemaElements::Relationship?

        def build_path_segment: (
          SchemaElements::Relationship,
          indexableType,
          ::Array[PathSegment],
          ::Array[::String]
        ) -> void

        def resolve_field: (SchemaElements::Relationship::ParentRef, indexableType, SchemaElements::Relationship, ::Array[::String]) -> SchemaElements::Field?
        def find_field_by_type: (indexableType, SchemaElements::Relationship, ::Array[::String]) -> SchemaElements::Field?
        def rel_description: (SchemaElements::Relationship) -> ::String
      end
    end
  end
end
