module ElasticGraph
  module SchemaDefinition
    module Indexing
      class TopLevelUpdateTargetResolver
        def initialize: (
          object_type: indexableType,
          resolved_relationship: ResolvedRelationship,
          sourced_fields: ::Array[SchemaElements::Field],
          field_path_resolver: SchemaElements::FieldPath::Resolver,
        ) -> void

        def resolve: () -> [SchemaArtifacts::RuntimeMetadata::UpdateTarget?, ::Array[::String]]

        private

        attr_reader object_type: indexableType
        attr_reader resolved_relationship: ResolvedRelationship
        attr_reader sourced_fields: ::Array[SchemaElements::Field]
        attr_reader field_path_resolver: SchemaElements::FieldPath::Resolver

        def validate_relationship: () -> ::Array[::String]
        def related_type: () -> indexableType
        def resolve_field_source: (UpdateTargetResolverSupport::_FieldSourceAdapter) -> [::String?, ::String?]
      end
    end
  end
end
